cargo-features = ["resolver"]

[workspace]
members = [
    # Core
    "consensus/aggregator",
    "consensus/elections",
    "finality/finality-gadget",
    "finality/runtime-companion",

    # Utils
    "utils/primitives",
    "utils/support",

]
resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[profile.test]
opt-level = 3
